export type ProductCategoriesToastTexts = {
  CATEGORIES_LOAD_ERROR_TITLE: string;
  CATEGORIES_LOAD_ERROR_MESSAGE: string;
  CATEGORY_ASSIGN_SUCCESS_TITLE: string;
  CATEGORY_UNASSIGN_SUCCESS_TITLE: string;
  CATEGORY_ASSIGN_ERROR_TITLE: string;
  CATEGORY_ASSIGN_ERROR_MESSAGE: string;
};
