import { DropdownOption } from '@ui/dropdown/models/dropdown.type';
import { ProductStatus } from '../../../pages/products/models/product-status.enum';
import { ProductType } from '../../../pages/products/models/product-type.enum';
import { ProductFormFieldIds } from '../models/product-form-field-ids.model';
import { ProductFormModel } from '../models/product-form.model';
import { ProductFormTexts } from '../models/product-form-texts.model';

export const PRODUCT_FORM_TEXTS: ProductFormTexts = {
  BASIC_INFORMATION_TITLE: 'Основна інформація',
  PRICING_INVENTORY_TITLE: 'Ціна та запаси',
  PRODUCT_NAME_LABEL: 'Назва товару',
  PRODUCT_NAME_PLACEHOLDER: 'напр. Лляна сорочка Coastal',
  PRODUCT_NAME_REQUIRED: 'Назва товару є обов’язковою.',
  PRODUCT_TYPE_LABEL: 'Тип товару',
  PRODUCT_TYPE_SIMPLE_LABEL: 'Простий',
  PRODUCT_TYPE_VARIABLE_LABEL: 'Варіативний',
  DESCRIPTION_LABEL: 'Опис',
  DESCRIPTION_PLACEHOLDER: 'Введіть опис товару...',
  PRICE_LABEL: 'Ціна ($)',
  PRICE_PLACEHOLDER: '0.00',
  OLD_PRICE_LABEL: 'Стара ціна (знижка)',
  OLD_PRICE_PLACEHOLDER: '0.00',
  SKU_LABEL: 'SKU',
  SKU_PLACEHOLDER: 'напр. CSTL-SHRT-01',
  STATUS_LABEL: 'Статус',
  AVAILABLE_LABEL: 'Доступний',
  CATEGORIES_TITLE: 'Категорії',
  ATTRIBUTES_TITLE: 'Атрибути',
  TAGS_TITLE: 'Теги',
  CATEGORIES_SEARCH_PLACEHOLDER: 'Пошук категорій...',
  ATTRIBUTES_SEARCH_PLACEHOLDER: 'Пошук атрибутів...',
  SIDEBAR_DISABLED_HINT: 'Спочатку створіть товар, щоб керувати категоріями, атрибутами та тегами.',
  ATTRIBUTES_SEARCH_LOADING: 'Завантаження атрибутів...',
  ATTRIBUTES_SEARCH_EMPTY: 'Атрибути не знайдено.',
  ATTRIBUTES_ASSIGNED_EMPTY: 'Ще немає призначених атрибутів.',
  TAGS_INPUT_PLACEHOLDER: 'Додати теги...',
  TAGS_SEARCH_LOADING: 'Завантаження тегів...',
  TAGS_SEARCH_EMPTY: 'Теги не знайдено.',
  TAGS_ASSIGNED_EMPTY: 'Ще немає призначених тегів.',
  IMAGES_TITLE: 'Медіа та файли',
  IMAGES_UPLOAD_LABEL: 'Завантажити',
  IMAGES_UPLOAD_LOADING_LABEL: 'Завантаження...',
  IMAGES_DROPZONE_HINT: 'Перетягніть зображення сюди або натисніть для вибору',
  IMAGES_ASSIGNED_EMPTY: 'Ще немає доданих зображень.',
  VARIATIONS_TITLE: 'Варіації товару',
  VARIATIONS_EMPTY: 'Ще немає доданих варіацій.',
  VARIATION_CARD_TITLE: 'Варіація',
  VARIATION_ADD_BUTTON_LABEL: 'Додати варіацію',
  VARIATION_CREATE_BUTTON_LABEL: 'Додати варіацію',
  VARIATION_CREATE_LOADING_BUTTON_LABEL: 'Збереження...',
  VARIATION_UPDATE_BUTTON_LABEL: 'Оновити варіацію',
  VARIATION_TITLE_LABEL: 'Заголовок',
  VARIATION_TITLE_PLACEHOLDER: 'напр. Варіант для синього кольору',
  VARIATION_NAME_LABEL: 'Назва варіації',
  VARIATION_NAME_PLACEHOLDER: 'напр. Синій / M',
  VARIATION_PRICE_LABEL: 'Ціна ($)',
  VARIATION_PRICE_PLACEHOLDER: '0.00',
  VARIATION_OLD_PRICE_LABEL: 'Стара ціна ($)',
  VARIATION_OLD_PRICE_PLACEHOLDER: '0.00',
  VARIATION_SKU_LABEL: 'SKU варіації',
  VARIATION_SKU_PLACEHOLDER: 'напр. CSTL-SHRT-BL-M',
  VARIATION_AVAILABLE_LABEL: 'Доступна',
  VARIATION_IS_MAIN_LABEL: 'Основна',
  VARIATION_ATTRIBUTES_TITLE: 'Атрибути варіації',
  VARIATION_ATTRIBUTES_SEARCH_PLACEHOLDER: 'Пошук атрибутів варіації...',
  VARIATION_ATTRIBUTES_SEARCH_LOADING: 'Завантаження атрибутів...',
  VARIATION_ATTRIBUTES_SEARCH_EMPTY: 'Атрибути не знайдено.',
  VARIATION_ATTRIBUTES_ASSIGNED_EMPTY: 'Ще немає атрибутів для варіації.',
  VARIATION_IMAGES_TITLE: 'Зображення варіації',
  VARIATION_IMAGES_DROPZONE_HINT: 'Перетягніть зображення для варіації або натисніть для вибору',
  VARIATION_IMAGES_ASSIGNED_EMPTY: 'Ще немає зображень для варіації.',
};

export const PRODUCT_FORM_FIELD_IDS: ProductFormFieldIds = {
  PRODUCT_NAME: 'product-name',
  PRODUCT_DESCRIPTION: 'product-description',
  PRICE: 'product-price',
  OLD_PRICE: 'product-old-price',
  SKU: 'product-sku',
  STATUS: 'product-status',
  TYPE_SIMPLE: 'product-type-simple',
  TYPE_VARIABLE: 'product-type-variable',
  AVAILABLE: 'product-available',
};

export const PRODUCT_FORM_STATUS_OPTIONS: DropdownOption[] = [
  { label: 'Чернетка', value: ProductStatus.Draft },
  { label: 'Активний', value: ProductStatus.Active },
  { label: 'Архівний', value: ProductStatus.Archived },
];

export const PRODUCT_FORM_DEFAULT_VALUE: ProductFormModel = {
  name: '',
  type: ProductType.Simple,
  description: '',
  price: '',
  oldPrice: '',
  sku: '',
  status: ProductStatus.Draft,
  available: true,
};
